name: NightPVP
main: Estem01\NightPvP\Night
version: 1.0
authors: [Estem0, Ihsan48, HenryDM, BilaldevPM, LadinoXx, UnknownNull]
api: 4.0.0
permissions:
 nightpvp.exempt.victim:
  default: op
  description: Exempt from protection during the day
 nightpvp.exempt.damager:
  default: op
  description: Can attack during the day
