name: NightPVP
main: Estem0\NightPVP
version: 4.6.0
author: Estem0
api: 1.0.0
load: POSTWORLD
permissions:
 nightpvp:
  default: op
  children:
   nightpvp.exempt:
    default: false
    description: Exempt from nightpvp
    children:
     nightpvp.exempt.victim:
      default: false
      description: Exempt from protection during the day
     nightpvp.exempt.damager:
      default: op
      description: Can attack during the day
