# ======================
#  GENERAL INFORMATIONS
# ======================

name: NightPVP
api: [4.0.0]
version: 1.2.0
main: Estem01\NightPvP\Main

# ======================
#   OTHER INFORMATIONS
# ======================

authors: [Estem0, Henry8K]
description: "A plugin to implement nightpvp on your server"