# ======================
#  GENERAL INFORMATIONS
# ======================

name: NightPVP
api: [5.0.0]
version: 1.3.2
main: Estem01\NightPvP\Main

# ======================
#   PERMISSION OPTIONS
# ======================

permissions:
  nightpvp.always.on:
    description: "Allows players to enable PvP at all times, ignoring night restrictions."
    default: false
  nightpvp.bypass:
    description: "Allows players to bypass PvP time restrictions and fight anytime."
    default: op

# ======================
#   OTHER INFORMATIONS
# ======================

authors: [Estem01, Henry8K, UnknownNull]
description: "A plugin that restricts PvP to nighttime only, with customizable worlds, times, and messages."
