# =====================
#      NIGHT PVP
# =====================

# resources/config.yml
# Worlds where NightPvP is active
allowed-worlds: 
  - "world"
  - "arena"

# Error message type (popup or message)
error-message-type: "popup"

# PvP restriction message
day-no-pvp: "§cYou can only fight during the night!"

# Custom world time settings
night-start-time: 13000  # Minecraft night start time
night-end-time: 23000    # Minecraft night end time

# Enable/disable world time check
enable-world-time-check: true

# Enable plugin logger
enable-logger: false
